### ISSUE TITLE
Some Requests and also a bug?

### ISSUE THREAD

**Issue by ghost** [certt/1000base#6]
When I compile the cheat and load it ingame on de_mirage I get these wierd shader bugs. Any Idea what that can be? 

SS: https://gyazo.com/03c06799345f0d84b1129f407ef85ebf

Also, how to add ON_GROUND statments in Createmove? (I'm newbie sry.) Is VMT going to be a problem with the new vacnet thing? 

In main menu when you press the key(delete) to open the menu the mouse dissapears and you can't see it until you go into a game.

**Comment by certt** [comment]
Valve make shitty "Panorama" update, they make a lot of bugs. I'll fix texture glitching with next patch, actually i wrote topic about this bug so you can fix it right now in your source (https://www.unknowncheats.me/forum/counterstrike-global-offensive/289470-texture-glitching-createstateblock-bug-fix.html).

You can get Entity flags with this func:
`EntityFlags GetFlags()
	{
		static int m_fFlags = g_pNetvars->GetOffset("DT_BasePlayer", "m_fFlags");
		return GetValue<EntityFlags>(m_fFlags);
	}`

`enum EntityFlags : int
{
	FL_ONGROUND = (1 << 0),
	FL_DUCKING = (1 << 1),
	FL_WATERJUMP = (1 << 2),
	FL_ONTRAIN = (1 << 3),
	FL_INRAIN = (1 << 4),
	FL_FROZEN = (1 << 5),
	FL_ATCONTROLS = (1 << 6),
	FL_CLIENT = (1 << 7),
	FL_FAKECLIENT = (1 << 8)
};`

I dont know how you wanna use it but here example how to make on_ground check.

`bool on_ground = (g_Globals->LocalPlayer->GetFlags() & FL_ONGROUND);`

**Comment by ghost** [comment]
Thanks crett! Ur awesome! I will use it for bhop.

**Comment by ghost** [comment]
@Crett what will The new patch contain?
